from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class YuhunAssets: 


	# Ocr Rule Assets
	# 第一行第一列的御魂等级 
	O_御魂等级14 = RuleOcr(roi=(474,182,46,22), area=(474,182,46,22), mode="Single", method="Default", keyword="御魂等级11", name="御魂等级14")
	#  
	O_御魂等级44 = RuleOcr(roi=(474,554,46,22), area=(474,554,46,22), mode="Single", method="Default", keyword="御魂等级14", name="御魂等级44")
	#  
	O_御魂等级41 = RuleOcr(roi=(122,554,46,22), area=(122,554,46,22), mode="Single", method="Default", keyword="御魂等级44", name="御魂等级41")
	#  
	O_御魂等级11 = RuleOcr(roi=(123,183,46,23), area=(123,183,46,23), mode="Single", method="Default", keyword="御魂等级11", name="御魂等级11")


	# Image Rule Assets
	#  
	I_YUNHUN11-UNSELECT = RuleImage(roi_front=(123,272,98,19), roi_back=(123,272,98,19), threshold=0.8, method="Template matching", file="./tasks/Yuhun/Yuhun_yunhun11-unselect.png")
	#  
	I_YUNHUN11-SELECT = RuleImage(roi_front=(123,272,98,19), roi_back=(123,272,98,19), threshold=0.9, method="Template matching", file="./tasks/Yuhun/Yuhun_yunhun11-select.png")
	#  
	I_QUANBUQIANGHUA = RuleImage(roi_front=(875,616,170,39), roi_back=(875,616,170,39), threshold=0.89, method="Template matching", file="./tasks/Yuhun/Yuhun_quanbuqianghua.png")
	#  
	I_JISUAN = RuleImage(roi_front=(1186,631,60,60), roi_back=(1186,631,60,60), threshold=0.8, method="Template matching", file="./tasks/Yuhun/Yuhun_jisuan.png")
	#  
	I_QIANGHUA = RuleImage(roi_front=(1186,631,60,60), roi_back=(1186,631,60,60), threshold=0.8, method="Template matching", file="./tasks/Yuhun/Yuhun_qianghua.png")


