from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class YuhunAssets: 


	# Image Rule Assets
	# 计算按钮（enhance_calc_dialog） 
	I_ENHANCE_CALC = RuleImage(roi_front=(1155,608,112,109), roi_back=(1155,608,112,109), threshold=0.8, method="Template matching", file="./tasks/Yuhun/enhance/enhance_calc.png")
	# 强化按钮（enhance_confirm） 
	I_ENHANCE_CONFIRM = RuleImage(roi_front=(1153,612,115,99), roi_back=(1153,612,115,99), threshold=0.8, method="Template matching", file="./tasks/Yuhun/enhance/enhance_confirm.png")


	# Click Rule Assets
	# 结果页点击第1个御魂 
	C_RESULT_SLOT_1 = RuleClick(roi_front=(200,72,263,260), roi_back=(200,72,263,260), name="result_slot_1")
	# 结果页点击第2个御魂 
	C_RESULT_SLOT_2 = RuleClick(roi_front=(498,72,263,260), roi_back=(498,72,263,260), name="result_slot_2")
	# 结果页点击第3个御魂 
	C_RESULT_SLOT_3 = RuleClick(roi_front=(796,72,263,260), roi_back=(796,72,263,260), name="result_slot_3")
	# 结果页点击第4个御魂 
	C_RESULT_SLOT_4 = RuleClick(roi_front=(200,367,263,260), roi_back=(200,367,263,260), name="result_slot_4")
	# 结果页点击第5个御魂 
	C_RESULT_SLOT_5 = RuleClick(roi_front=(498,367,263,260), roi_back=(498,367,263,260), name="result_slot_5")
	# 结果页点击第6个御魂 
	C_RESULT_SLOT_6 = RuleClick(roi_front=(796,367,263,260), roi_back=(796,367,263,260), name="result_slot_6")


	# Image Rule Assets
	# 结果页·强化按钮 
	I_RESULT_CONFIRM_ENHANCE = RuleImage(roi_front=(852,590,110,100), roi_back=(852,590,110,100), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_confirm_enhance.png")
	# 结果页·计算按钮 
	I_RESULT_CALC = RuleImage(roi_front=(852,590,110,100), roi_back=(852,590,110,100), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_calc.png")
	# 结果页·继续强化图标 
	I_RESULT_ENHANCE = RuleImage(roi_front=(1157,571,103,104), roi_back=(1157,571,103,104), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_enhance.png")
	# 结果页·弃置按钮 
	I_RESULT_DISCARD = RuleImage(roi_front=(1168,374,71,68), roi_back=(1168,374,71,68), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_discard.png")
	# 结果页·恢复按钮 
	I_RESULT_RESTORE = RuleImage(roi_front=(1168,468,71,69), roi_back=(1168,468,71,69), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_restore.png")
	# 结果页·御魂选中状态模板 
	I_RESULT_SOUL_SELECTED_TEMPLATE = RuleImage(roi_front=(200,320,26,20), roi_back=(200,320,26,20), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_selected.png")
	# 结果页第1个御魂御魂选中状态 
	I_RESULT_SOUL_SELECTED_1 = RuleImage(roi_front=(200,320,26,20), roi_back=(200,320,26,20), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_selected.png")
	# 结果页第2个御魂御魂选中状态 
	I_RESULT_SOUL_SELECTED_2 = RuleImage(roi_front=(498,320,26,20), roi_back=(498,320,26,20), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_selected.png")
	# 结果页第3个御魂御魂选中状态 
	I_RESULT_SOUL_SELECTED_3 = RuleImage(roi_front=(796,320,26,20), roi_back=(796,320,26,20), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_selected.png")
	# 结果页第4个御魂御魂选中状态 
	I_RESULT_SOUL_SELECTED_4 = RuleImage(roi_front=(200,615,26,20), roi_back=(200,615,26,20), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_selected.png")
	# 结果页第5个御魂御魂选中状态 
	I_RESULT_SOUL_SELECTED_5 = RuleImage(roi_front=(498,615,26,20), roi_back=(498,615,26,20), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_selected.png")
	# 结果页第6个御魂御魂选中状态 
	I_RESULT_SOUL_SELECTED_6 = RuleImage(roi_front=(796,615,26,20), roi_back=(796,615,26,20), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_selected.png")
	# 结果页·御魂弃置状态模板 
	I_RESULT_SOUL_DISCARDED_TEMPLATE = RuleImage(roi_front=(417,372,28,28), roi_back=(417,372,28,28), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_discarded.png")
	# 结果页第1个御魂御魂弃置状态 
	I_RESULT_SOUL_DISCARDED_1 = RuleImage(roi_front=(417,77,28,28), roi_back=(417,77,28,28), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_discarded.png")
	# 结果页第2个御魂御魂弃置状态 
	I_RESULT_SOUL_DISCARDED_2 = RuleImage(roi_front=(715,77,28,28), roi_back=(715,77,28,28), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_discarded.png")
	# 结果页第3个御魂御魂弃置状态 
	I_RESULT_SOUL_DISCARDED_3 = RuleImage(roi_front=(1013,77,28,28), roi_back=(1013,77,28,28), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_discarded.png")
	# 结果页第4个御魂御魂弃置状态 
	I_RESULT_SOUL_DISCARDED_4 = RuleImage(roi_front=(417,372,28,28), roi_back=(417,372,28,28), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_discarded.png")
	# 结果页第5个御魂御魂弃置状态 
	I_RESULT_SOUL_DISCARDED_5 = RuleImage(roi_front=(715,372,28,28), roi_back=(715,372,28,28), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_discarded.png")
	# 结果页第6个御魂御魂弃置状态 
	I_RESULT_SOUL_DISCARDED_6 = RuleImage(roi_front=(1013,372,28,28), roi_back=(1013,372,28,28), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_soul_discarded.png")
	# 结果页第1个御魂副属性3强化标识 
	I_RESULT_SLOT_1_SUB_ATTR_3_BONUS = RuleImage(roi_front=(376,251,20,30), roi_back=(376,251,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第1个御魂副属性1强化标识 
	I_RESULT_SLOT_1_SUB_ATTR_1_BONUS = RuleImage(roi_front=(376,185,20,30), roi_back=(376,185,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第1个御魂副属性2强化标识 
	I_RESULT_SLOT_1_SUB_ATTR_2_BONUS = RuleImage(roi_front=(376,218,20,30), roi_back=(376,218,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第1个御魂副属性4强化标识 
	I_RESULT_SLOT_1_SUB_ATTR_4_BONUS = RuleImage(roi_front=(376,284,20,30), roi_back=(376,284,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第2个御魂副属性3强化标识 
	I_RESULT_SLOT_2_SUB_ATTR_3_BONUS = RuleImage(roi_front=(674,251,20,30), roi_back=(674,251,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第2个御魂副属性1强化标识 
	I_RESULT_SLOT_2_SUB_ATTR_1_BONUS = RuleImage(roi_front=(674,185,20,30), roi_back=(674,185,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第2个御魂副属性2强化标识 
	I_RESULT_SLOT_2_SUB_ATTR_2_BONUS = RuleImage(roi_front=(674,218,20,30), roi_back=(674,218,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第2个御魂副属性4强化标识 
	I_RESULT_SLOT_2_SUB_ATTR_4_BONUS = RuleImage(roi_front=(674,284,20,30), roi_back=(674,284,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第3个御魂副属性3强化标识 
	I_RESULT_SLOT_3_SUB_ATTR_3_BONUS = RuleImage(roi_front=(972,251,20,30), roi_back=(972,251,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第3个御魂副属性1强化标识 
	I_RESULT_SLOT_3_SUB_ATTR_1_BONUS = RuleImage(roi_front=(972,185,20,30), roi_back=(972,185,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第3个御魂副属性2强化标识 
	I_RESULT_SLOT_3_SUB_ATTR_2_BONUS = RuleImage(roi_front=(972,218,20,30), roi_back=(972,218,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第3个御魂副属性4强化标识 
	I_RESULT_SLOT_3_SUB_ATTR_4_BONUS = RuleImage(roi_front=(972,284,20,30), roi_back=(972,284,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第4个御魂副属性3强化标识 
	I_RESULT_SLOT_4_SUB_ATTR_3_BONUS = RuleImage(roi_front=(376,546,20,30), roi_back=(376,546,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第4个御魂副属性1强化标识 
	I_RESULT_SLOT_4_SUB_ATTR_1_BONUS = RuleImage(roi_front=(376,480,20,30), roi_back=(376,480,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第4个御魂副属性2强化标识 
	I_RESULT_SLOT_4_SUB_ATTR_2_BONUS = RuleImage(roi_front=(376,513,20,30), roi_back=(376,513,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第4个御魂副属性4强化标识 
	I_RESULT_SLOT_4_SUB_ATTR_4_BONUS = RuleImage(roi_front=(376,579,20,30), roi_back=(376,579,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第5个御魂副属性3强化标识 
	I_RESULT_SLOT_5_SUB_ATTR_3_BONUS = RuleImage(roi_front=(674,546,20,30), roi_back=(674,546,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第5个御魂副属性1强化标识 
	I_RESULT_SLOT_5_SUB_ATTR_1_BONUS = RuleImage(roi_front=(674,480,20,30), roi_back=(674,480,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第5个御魂副属性2强化标识 
	I_RESULT_SLOT_5_SUB_ATTR_2_BONUS = RuleImage(roi_front=(674,513,20,30), roi_back=(674,513,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第5个御魂副属性4强化标识 
	I_RESULT_SLOT_5_SUB_ATTR_4_BONUS = RuleImage(roi_front=(674,579,20,30), roi_back=(674,579,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第6个御魂副属性3强化标识 
	I_RESULT_SLOT_6_SUB_ATTR_3_BONUS = RuleImage(roi_front=(972,546,20,30), roi_back=(972,546,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第6个御魂副属性1强化标识 
	I_RESULT_SLOT_6_SUB_ATTR_1_BONUS = RuleImage(roi_front=(972,480,20,30), roi_back=(972,480,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第6个御魂副属性2强化标识 
	I_RESULT_SLOT_6_SUB_ATTR_2_BONUS = RuleImage(roi_front=(972,513,20,30), roi_back=(972,513,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")
	# 结果页第6个御魂副属性4强化标识 
	I_RESULT_SLOT_6_SUB_ATTR_4_BONUS = RuleImage(roi_front=(972,579,20,30), roi_back=(972,579,20,30), threshold=0.8, method="Template matching", file="./tasks/Yuhun/result/result_sub_attr_bonus.png")


	# Ocr Rule Assets
	# 结果页第1个御魂主属性名称 
	O_RESULT_SLOT_1_MAIN_ATTR = RuleOcr(roi=(215,147,90,28), area=(215,147,90,28), mode="Single", method="Default", keyword="", name="result_slot_1_main_attr")
	# 结果页第1个御魂副属性1 
	O_RESULT_SLOT_1_SUB_ATTR_1 = RuleOcr(roi=(213,185,160,30), area=(213,185,160,30), mode="Single", method="Default", keyword="", name="result_slot_1_sub_attr_1")
	# 结果页第1个御魂副属性1强化数值 
	O_RESULT_SLOT_1_SUB_ATTR_1_BONUS_VALUE = RuleOcr(roi=(395,185,60,30), area=(395,185,60,30), mode="Single", method="Default", keyword="", name="result_slot_1_sub_attr_1_bonus_value")
	# 结果页第1个御魂副属性2 
	O_RESULT_SLOT_1_SUB_ATTR_2 = RuleOcr(roi=(213,218,160,30), area=(213,218,160,30), mode="Single", method="Default", keyword="", name="result_slot_1_sub_attr_2")
	# 结果页第1个御魂副属性2强化数值 
	O_RESULT_SLOT_1_SUB_ATTR_2_BONUS_VALUE = RuleOcr(roi=(395,218,60,30), area=(395,218,60,30), mode="Single", method="Default", keyword="", name="result_slot_1_sub_attr_2_bonus_value")
	# 结果页第1个御魂副属性3 
	O_RESULT_SLOT_1_SUB_ATTR_3 = RuleOcr(roi=(213,251,160,30), area=(213,251,160,30), mode="Single", method="Default", keyword="", name="result_slot_1_sub_attr_3")
	# 结果页第1个御魂副属性3强化数值 
	O_RESULT_SLOT_1_SUB_ATTR_3_BONUS_VALUE = RuleOcr(roi=(395,251,60,30), area=(395,251,60,30), mode="Single", method="Default", keyword="", name="result_slot_1_sub_attr_3_bonus_value")
	# 结果页第1个御魂副属性4 
	O_RESULT_SLOT_1_SUB_ATTR_4 = RuleOcr(roi=(213,284,160,30), area=(213,284,160,30), mode="Single", method="Default", keyword="", name="result_slot_1_sub_attr_4")
	# 结果页第1个御魂副属性4强化数值 
	O_RESULT_SLOT_1_SUB_ATTR_4_BONUS_VALUE = RuleOcr(roi=(395,284,60,30), area=(395,284,60,30), mode="Single", method="Default", keyword="", name="result_slot_1_sub_attr_4_bonus_value")
	# 结果页第2个御魂主属性名称 
	O_RESULT_SLOT_2_MAIN_ATTR = RuleOcr(roi=(513,147,90,28), area=(513,147,90,28), mode="Single", method="Default", keyword="", name="result_slot_2_main_attr")
	# 结果页第2个御魂副属性1 
	O_RESULT_SLOT_2_SUB_ATTR_1 = RuleOcr(roi=(511,185,160,30), area=(511,185,160,30), mode="Single", method="Default", keyword="", name="result_slot_2_sub_attr_1")
	# 结果页第2个御魂副属性1强化数值 
	O_RESULT_SLOT_2_SUB_ATTR_1_BONUS_VALUE = RuleOcr(roi=(693,185,60,30), area=(693,185,60,30), mode="Single", method="Default", keyword="", name="result_slot_2_sub_attr_1_bonus_value")
	# 结果页第2个御魂副属性2 
	O_RESULT_SLOT_2_SUB_ATTR_2 = RuleOcr(roi=(511,218,160,30), area=(511,218,160,30), mode="Single", method="Default", keyword="", name="result_slot_2_sub_attr_2")
	# 结果页第2个御魂副属性2强化数值 
	O_RESULT_SLOT_2_SUB_ATTR_2_BONUS_VALUE = RuleOcr(roi=(693,218,60,30), area=(693,218,60,30), mode="Single", method="Default", keyword="", name="result_slot_2_sub_attr_2_bonus_value")
	# 结果页第2个御魂副属性3 
	O_RESULT_SLOT_2_SUB_ATTR_3 = RuleOcr(roi=(511,251,160,30), area=(511,251,160,30), mode="Single", method="Default", keyword="", name="result_slot_2_sub_attr_3")
	# 结果页第2个御魂副属性3强化数值 
	O_RESULT_SLOT_2_SUB_ATTR_3_BONUS_VALUE = RuleOcr(roi=(693,251,60,30), area=(693,251,60,30), mode="Single", method="Default", keyword="", name="result_slot_2_sub_attr_3_bonus_value")
	# 结果页第2个御魂副属性4 
	O_RESULT_SLOT_2_SUB_ATTR_4 = RuleOcr(roi=(511,284,160,30), area=(511,284,160,30), mode="Single", method="Default", keyword="", name="result_slot_2_sub_attr_4")
	# 结果页第2个御魂副属性4强化数值 
	O_RESULT_SLOT_2_SUB_ATTR_4_BONUS_VALUE = RuleOcr(roi=(693,284,60,30), area=(693,284,60,30), mode="Single", method="Default", keyword="", name="result_slot_2_sub_attr_4_bonus_value")
	# 结果页第3个御魂主属性名称 
	O_RESULT_SLOT_3_MAIN_ATTR = RuleOcr(roi=(811,147,90,28), area=(811,147,90,28), mode="Single", method="Default", keyword="", name="result_slot_3_main_attr")
	# 结果页第3个御魂副属性1 
	O_RESULT_SLOT_3_SUB_ATTR_1 = RuleOcr(roi=(809,185,160,30), area=(809,185,160,30), mode="Single", method="Default", keyword="", name="result_slot_3_sub_attr_1")
	# 结果页第3个御魂副属性1强化数值 
	O_RESULT_SLOT_3_SUB_ATTR_1_BONUS_VALUE = RuleOcr(roi=(991,185,60,30), area=(991,185,60,30), mode="Single", method="Default", keyword="", name="result_slot_3_sub_attr_1_bonus_value")
	# 结果页第3个御魂副属性2 
	O_RESULT_SLOT_3_SUB_ATTR_2 = RuleOcr(roi=(809,218,160,30), area=(809,218,160,30), mode="Single", method="Default", keyword="", name="result_slot_3_sub_attr_2")
	# 结果页第3个御魂副属性2强化数值 
	O_RESULT_SLOT_3_SUB_ATTR_2_BONUS_VALUE = RuleOcr(roi=(991,218,60,30), area=(991,218,60,30), mode="Single", method="Default", keyword="", name="result_slot_3_sub_attr_2_bonus_value")
	# 结果页第3个御魂副属性3 
	O_RESULT_SLOT_3_SUB_ATTR_3 = RuleOcr(roi=(809,251,160,30), area=(809,251,160,30), mode="Single", method="Default", keyword="", name="result_slot_3_sub_attr_3")
	# 结果页第3个御魂副属性3强化数值 
	O_RESULT_SLOT_3_SUB_ATTR_3_BONUS_VALUE = RuleOcr(roi=(991,251,60,30), area=(991,251,60,30), mode="Single", method="Default", keyword="", name="result_slot_3_sub_attr_3_bonus_value")
	# 结果页第3个御魂副属性4 
	O_RESULT_SLOT_3_SUB_ATTR_4 = RuleOcr(roi=(809,284,160,30), area=(809,284,160,30), mode="Single", method="Default", keyword="", name="result_slot_3_sub_attr_4")
	# 结果页第3个御魂副属性4强化数值 
	O_RESULT_SLOT_3_SUB_ATTR_4_BONUS_VALUE = RuleOcr(roi=(991,284,60,30), area=(991,284,60,30), mode="Single", method="Default", keyword="", name="result_slot_3_sub_attr_4_bonus_value")
	# 结果页第4个御魂主属性名称 
	O_RESULT_SLOT_4_MAIN_ATTR = RuleOcr(roi=(215,442,90,28), area=(215,442,90,28), mode="Single", method="Default", keyword="", name="result_slot_4_main_attr")
	# 结果页第4个御魂副属性1 
	O_RESULT_SLOT_4_SUB_ATTR_1 = RuleOcr(roi=(213,480,160,30), area=(213,480,160,30), mode="Single", method="Default", keyword="", name="result_slot_4_sub_attr_1")
	# 结果页第4个御魂副属性1强化数值 
	O_RESULT_SLOT_4_SUB_ATTR_1_BONUS_VALUE = RuleOcr(roi=(395,480,60,30), area=(395,480,60,30), mode="Single", method="Default", keyword="", name="result_slot_4_sub_attr_1_bonus_value")
	# 结果页第4个御魂副属性2 
	O_RESULT_SLOT_4_SUB_ATTR_2 = RuleOcr(roi=(213,513,160,30), area=(213,513,160,30), mode="Single", method="Default", keyword="", name="result_slot_4_sub_attr_2")
	# 结果页第4个御魂副属性2强化数值 
	O_RESULT_SLOT_4_SUB_ATTR_2_BONUS_VALUE = RuleOcr(roi=(395,513,60,30), area=(395,513,60,30), mode="Single", method="Default", keyword="", name="result_slot_4_sub_attr_2_bonus_value")
	# 结果页第4个御魂副属性3 
	O_RESULT_SLOT_4_SUB_ATTR_3 = RuleOcr(roi=(213,546,160,30), area=(213,546,160,30), mode="Single", method="Default", keyword="", name="result_slot_4_sub_attr_3")
	# 结果页第4个御魂副属性3强化数值 
	O_RESULT_SLOT_4_SUB_ATTR_3_BONUS_VALUE = RuleOcr(roi=(395,546,60,30), area=(395,546,60,30), mode="Single", method="Default", keyword="", name="result_slot_4_sub_attr_3_bonus_value")
	# 结果页第4个御魂副属性4 
	O_RESULT_SLOT_4_SUB_ATTR_4 = RuleOcr(roi=(213,579,160,30), area=(213,579,160,30), mode="Single", method="Default", keyword="", name="result_slot_4_sub_attr_4")
	# 结果页第4个御魂副属性4强化数值 
	O_RESULT_SLOT_4_SUB_ATTR_4_BONUS_VALUE = RuleOcr(roi=(395,579,60,30), area=(395,579,60,30), mode="Single", method="Default", keyword="", name="result_slot_4_sub_attr_4_bonus_value")
	# 结果页第5个御魂主属性名称 
	O_RESULT_SLOT_5_MAIN_ATTR = RuleOcr(roi=(513,442,90,28), area=(513,442,90,28), mode="Single", method="Default", keyword="", name="result_slot_5_main_attr")
	# 结果页第5个御魂副属性1 
	O_RESULT_SLOT_5_SUB_ATTR_1 = RuleOcr(roi=(511,480,160,30), area=(511,480,160,30), mode="Single", method="Default", keyword="", name="result_slot_5_sub_attr_1")
	# 结果页第5个御魂副属性1强化数值 
	O_RESULT_SLOT_5_SUB_ATTR_1_BONUS_VALUE = RuleOcr(roi=(693,480,60,30), area=(693,480,60,30), mode="Single", method="Default", keyword="", name="result_slot_5_sub_attr_1_bonus_value")
	# 结果页第5个御魂副属性2 
	O_RESULT_SLOT_5_SUB_ATTR_2 = RuleOcr(roi=(511,513,160,30), area=(511,513,160,30), mode="Single", method="Default", keyword="", name="result_slot_5_sub_attr_2")
	# 结果页第5个御魂副属性2强化数值 
	O_RESULT_SLOT_5_SUB_ATTR_2_BONUS_VALUE = RuleOcr(roi=(693,513,60,30), area=(693,513,60,30), mode="Single", method="Default", keyword="", name="result_slot_5_sub_attr_2_bonus_value")
	# 结果页第5个御魂副属性3 
	O_RESULT_SLOT_5_SUB_ATTR_3 = RuleOcr(roi=(511,546,160,30), area=(511,546,160,30), mode="Single", method="Default", keyword="", name="result_slot_5_sub_attr_3")
	# 结果页第5个御魂副属性3强化数值 
	O_RESULT_SLOT_5_SUB_ATTR_3_BONUS_VALUE = RuleOcr(roi=(693,546,60,30), area=(693,546,60,30), mode="Single", method="Default", keyword="", name="result_slot_5_sub_attr_3_bonus_value")
	# 结果页第5个御魂副属性4 
	O_RESULT_SLOT_5_SUB_ATTR_4 = RuleOcr(roi=(511,579,160,30), area=(511,579,160,30), mode="Single", method="Default", keyword="", name="result_slot_5_sub_attr_4")
	# 结果页第5个御魂副属性4强化数值 
	O_RESULT_SLOT_5_SUB_ATTR_4_BONUS_VALUE = RuleOcr(roi=(693,579,60,30), area=(693,579,60,30), mode="Single", method="Default", keyword="", name="result_slot_5_sub_attr_4_bonus_value")
	# 结果页第6个御魂主属性名称 
	O_RESULT_SLOT_6_MAIN_ATTR = RuleOcr(roi=(811,442,90,28), area=(811,442,90,28), mode="Single", method="Default", keyword="", name="result_slot_6_main_attr")
	# 结果页第6个御魂副属性1 
	O_RESULT_SLOT_6_SUB_ATTR_1 = RuleOcr(roi=(809,480,160,30), area=(809,480,160,30), mode="Single", method="Default", keyword="", name="result_slot_6_sub_attr_1")
	# 结果页第6个御魂副属性1强化数值 
	O_RESULT_SLOT_6_SUB_ATTR_1_BONUS_VALUE = RuleOcr(roi=(991,480,60,30), area=(991,480,60,30), mode="Single", method="Default", keyword="", name="result_slot_6_sub_attr_1_bonus_value")
	# 结果页第6个御魂副属性2 
	O_RESULT_SLOT_6_SUB_ATTR_2 = RuleOcr(roi=(809,513,160,30), area=(809,513,160,30), mode="Single", method="Default", keyword="", name="result_slot_6_sub_attr_2")
	# 结果页第6个御魂副属性2强化数值 
	O_RESULT_SLOT_6_SUB_ATTR_2_BONUS_VALUE = RuleOcr(roi=(991,513,60,30), area=(991,513,60,30), mode="Single", method="Default", keyword="", name="result_slot_6_sub_attr_2_bonus_value")
	# 结果页第6个御魂副属性3 
	O_RESULT_SLOT_6_SUB_ATTR_3 = RuleOcr(roi=(809,546,160,30), area=(809,546,160,30), mode="Single", method="Default", keyword="", name="result_slot_6_sub_attr_3")
	# 结果页第6个御魂副属性3强化数值 
	O_RESULT_SLOT_6_SUB_ATTR_3_BONUS_VALUE = RuleOcr(roi=(991,546,60,30), area=(991,546,60,30), mode="Single", method="Default", keyword="", name="result_slot_6_sub_attr_3_bonus_value")
	# 结果页第6个御魂副属性4 
	O_RESULT_SLOT_6_SUB_ATTR_4 = RuleOcr(roi=(809,579,160,30), area=(809,579,160,30), mode="Single", method="Default", keyword="", name="result_slot_6_sub_attr_4")
	# 结果页第6个御魂副属性4强化数值 
	O_RESULT_SLOT_6_SUB_ATTR_4_BONUS_VALUE = RuleOcr(roi=(991,579,60,30), area=(991,579,60,30), mode="Single", method="Default", keyword="", name="result_slot_6_sub_attr_4_bonus_value")


	# Click Rule Assets
	# 点击列表第1个御魂 
	C_SLOT_1 = RuleClick(roi_front=(124,185,99,103), roi_back=(124,185,99,103), name="slot_1")
	# 点击列表第2个御魂 
	C_SLOT_2 = RuleClick(roi_front=(241,185,99,103), roi_back=(241,185,99,103), name="slot_2")
	# 点击列表第3个御魂 
	C_SLOT_3 = RuleClick(roi_front=(358,185,99,103), roi_back=(358,185,99,103), name="slot_3")
	# 点击列表第4个御魂 
	C_SLOT_4 = RuleClick(roi_front=(475,185,99,103), roi_back=(475,185,99,103), name="slot_4")
	# 点击列表第5个御魂 
	C_SLOT_5 = RuleClick(roi_front=(124,309,99,103), roi_back=(124,309,99,103), name="slot_5")
	# 点击列表第6个御魂 
	C_SLOT_6 = RuleClick(roi_front=(241,309,99,103), roi_back=(241,309,99,103), name="slot_6")
	# 点击列表第7个御魂 
	C_SLOT_7 = RuleClick(roi_front=(358,309,99,103), roi_back=(358,309,99,103), name="slot_7")
	# 点击列表第8个御魂 
	C_SLOT_8 = RuleClick(roi_front=(475,309,99,103), roi_back=(475,309,99,103), name="slot_8")
	# 点击列表第9个御魂 
	C_SLOT_9 = RuleClick(roi_front=(124,433,99,103), roi_back=(124,433,99,103), name="slot_9")
	# 点击列表第10个御魂 
	C_SLOT_10 = RuleClick(roi_front=(241,433,99,103), roi_back=(241,433,99,103), name="slot_10")
	# 点击列表第11个御魂 
	C_SLOT_11 = RuleClick(roi_front=(358,433,99,103), roi_back=(358,433,99,103), name="slot_11")
	# 点击列表第12个御魂 
	C_SLOT_12 = RuleClick(roi_front=(475,433,99,103), roi_back=(475,433,99,103), name="slot_12")
	# 点击列表第13个御魂 
	C_SLOT_13 = RuleClick(roi_front=(124,557,99,103), roi_back=(124,557,99,103), name="slot_13")
	# 点击列表第14个御魂 
	C_SLOT_14 = RuleClick(roi_front=(241,557,99,103), roi_back=(241,557,99,103), name="slot_14")
	# 点击列表第15个御魂 
	C_SLOT_15 = RuleClick(roi_front=(358,557,99,103), roi_back=(358,557,99,103), name="slot_15")
	# 点击列表第16个御魂 
	C_SLOT_16 = RuleClick(roi_front=(475,557,99,103), roi_back=(475,557,99,103), name="slot_16")


	# Image Rule Assets
	# 右下角全部强化 
	I_SELECT_ENHANCE_ALL = RuleImage(roi_front=(912,611,132,48), roi_back=(912,611,132,48), threshold=0.89, method="Template matching", file="./tasks/Yuhun/select/select_enhance_all.png")
	# 选中标记模板（从已选中的1号位裁剪） 
	I_SELECT_SLOT_SELECTED_TEMPLATE = RuleImage(roi_front=(186,189,36,20), roi_back=(186,189,36,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第1个御魂是否已选中 
	I_SELECT_SLOT_1_SELECTED = RuleImage(roi_front=(198,194,30,20), roi_back=(198,194,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第2个御魂是否已选中 
	I_SELECT_SLOT_2_SELECTED = RuleImage(roi_front=(315,194,30,20), roi_back=(315,194,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第3个御魂是否已选中 
	I_SELECT_SLOT_3_SELECTED = RuleImage(roi_front=(432,194,30,20), roi_back=(432,194,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第4个御魂是否已选中 
	I_SELECT_SLOT_4_SELECTED = RuleImage(roi_front=(549,194,30,20), roi_back=(549,194,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第5个御魂是否已选中 
	I_SELECT_SLOT_5_SELECTED = RuleImage(roi_front=(198,318,30,20), roi_back=(198,318,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第6个御魂是否已选中 
	I_SELECT_SLOT_6_SELECTED = RuleImage(roi_front=(315,318,30,20), roi_back=(315,318,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第7个御魂是否已选中 
	I_SELECT_SLOT_7_SELECTED = RuleImage(roi_front=(432,318,30,20), roi_back=(432,318,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第8个御魂是否已选中 
	I_SELECT_SLOT_8_SELECTED = RuleImage(roi_front=(549,318,30,20), roi_back=(549,318,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第9个御魂是否已选中 
	I_SELECT_SLOT_9_SELECTED = RuleImage(roi_front=(198,442,30,20), roi_back=(198,442,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第10个御魂是否已选中 
	I_SELECT_SLOT_10_SELECTED = RuleImage(roi_front=(315,442,30,20), roi_back=(315,442,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第11个御魂是否已选中 
	I_SELECT_SLOT_11_SELECTED = RuleImage(roi_front=(432,442,30,20), roi_back=(432,442,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第12个御魂是否已选中 
	I_SELECT_SLOT_12_SELECTED = RuleImage(roi_front=(549,442,30,20), roi_back=(549,442,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第13个御魂是否已选中 
	I_SELECT_SLOT_13_SELECTED = RuleImage(roi_front=(198,566,30,20), roi_back=(198,566,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第14个御魂是否已选中 
	I_SELECT_SLOT_14_SELECTED = RuleImage(roi_front=(315,566,30,20), roi_back=(315,566,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第15个御魂是否已选中 
	I_SELECT_SLOT_15_SELECTED = RuleImage(roi_front=(432,566,30,20), roi_back=(432,566,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")
	# 列表第16个御魂是否已选中 
	I_SELECT_SLOT_16_SELECTED = RuleImage(roi_front=(549,566,30,20), roi_back=(549,566,30,20), threshold=0.4, method="Template matching", file="./tasks/Yuhun/select/select_slot_selected.png")


	# Ocr Rule Assets
	# 详情弹窗御魂类型 + level 
	O_SOUL_TYPE_LEVEL = RuleOcr(roi=(680,230,150,26), area=(680,230,150,26), mode="Single", method="Default", keyword="", name="soul_type_level")
	# 确认强化御魂数量 (N/12) 
	O_SELECT_CONFIRM_COUNT = RuleOcr(roi=(875,116,65,25), area=(875,116,65,25), mode="Single", method="Default", keyword="", name="select_confirm_count")
	# 选中御魂后主属性 
	O_DETAIL_MAIN_ATTR = RuleOcr(roi=(605,308,120,29), area=(605,308,120,29), mode="Single", method="Default", keyword="", name="detail_main_attr")
	# 副属性行1 
	O_DETAIL_SUB_ATTR_1 = RuleOcr(roi=(605,340,300,29), area=(605,340,300,29), mode="Single", method="Default", keyword="", name="detail_sub_attr_1")
	# 副属性行2 
	O_DETAIL_SUB_ATTR_2 = RuleOcr(roi=(605,370,300,29), area=(605,370,300,29), mode="Single", method="Default", keyword="", name="detail_sub_attr_2")
	# 副属性行3 
	O_DETAIL_SUB_ATTR_3 = RuleOcr(roi=(605,402,300,29), area=(605,402,300,29), mode="Single", method="Default", keyword="", name="detail_sub_attr_3")
	# 副属性行4 
	O_DETAIL_SUB_ATTR_4 = RuleOcr(roi=(605,434,300,29), area=(605,434,300,29), mode="Single", method="Default", keyword="", name="detail_sub_attr_4")


